## Teste de Tensor Flow

In [2]:
!pip install tensorflow

  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
     ---------------------------------------- 0.0/48.7 kB ? eta -:--:--
     ---------------------------------------- 48.7/48.7 kB 2.6 MB/s eta 0:00:00
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 0.5/390.3 MB 14.5 MB/s eta 0:00:27
   ---------------------------------------- 1.0/390.3 MB 12.7 MB/s eta 0:00:31
   ---------------------------------------- 1.5/390.3

In [3]:
import tensorflow as tf

In [4]:
a = tf.constant(20)

In [5]:
b = tf.Variable(30)

In [6]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [7]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=30>

In [8]:
c = a * b

In [9]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=600>

In [12]:
@tf.function
def soma( x, y ):
    z = x + y
    print(z)
    return z

In [13]:
soma(10, 20)

30


<tf.Tensor: shape=(), dtype=int32, numpy=30>