In [1]:
#!pip install numpy

In [2]:
import numpy as np

In [11]:
v1 = np.array([5, 10, 15, 20, 45, 2], dtype=np.float64)

In [12]:
v1

array([ 5., 10., 15., 20., 45.,  2.])

In [17]:
v1.ndim

1

In [18]:
v1.shape

(6,)

In [19]:
v1.dtype

dtype('float64')

In [20]:
m1 = np.array(  [   [ 7, 3, 8 ], [ 14, 18, 15 ], [ 22, 35, 63 ]   ], dtype=np.uint8 )

In [23]:
m1

array([[ 7,  3,  8],
       [14, 18, 15],
       [22, 35, 63]], dtype=uint8)

In [22]:
m1.ndim

2

In [24]:
m1.shape

(3, 3)

In [25]:
m1.dtype

dtype('uint8')

In [28]:
m2 = np.array([ [7 ,3 , 8], [0, 0, 0], [14, 18, 19], [22, 35, 63]])

In [29]:
m2

array([[ 7,  3,  8],
       [ 0,  0,  0],
       [14, 18, 19],
       [22, 35, 63]])

In [30]:
m2.ndim

2

In [31]:
m2.shape

(4, 3)

In [39]:
np.zeros( (7, 10, 2,  4) )

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0

In [40]:
np.zeros( (6, 2) )

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
np.zeros( (2,6 ))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
np.ones( (2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones( (6, 2) )

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Ex1: 
Crie vetor numpy para conter as notas de um aluno em 1 disciplina especifica, assumindo que a disciplina possua 4 notas. O vetor deve ser preenchido com notas a sua escolha. Uma vez criado mostre na tela a quantidade de dimensões e o shape do vetor

In [44]:
# Minhas notas em matematica
notas = np.array( [8.2, 6.5, 9.1, 3.3] )

In [45]:
notas

array([8.2, 6.5, 9.1, 3.3])

In [46]:
notas.ndim 

1

In [47]:
notas.shape

(4,)

In [48]:
notas.dtype

dtype('float64')

### Ex2: 
Crie uma matriz para guardar as notas de 1 aluno nas 6 disciplinas do semestre, esta matriz deve ser preenchida com notas 1 (um). Uma vez criada mostre na tela a quantidade de dimensões e o shape da matriz


In [55]:
m1 = np.ones( (6, 4) )

In [56]:
m1.ndim

2

In [57]:
m1.shape

(6, 4)

In [58]:
m1.dtype

dtype('float64')

In [63]:
v2 = np.arange( -10, 10, 0.1 )

In [64]:
v2

array([-1.00000000e+01, -9.90000000e+00, -9.80000000e+00, -9.70000000e+00,
       -9.60000000e+00, -9.50000000e+00, -9.40000000e+00, -9.30000000e+00,
       -9.20000000e+00, -9.10000000e+00, -9.00000000e+00, -8.90000000e+00,
       -8.80000000e+00, -8.70000000e+00, -8.60000000e+00, -8.50000000e+00,
       -8.40000000e+00, -8.30000000e+00, -8.20000000e+00, -8.10000000e+00,
       -8.00000000e+00, -7.90000000e+00, -7.80000000e+00, -7.70000000e+00,
       -7.60000000e+00, -7.50000000e+00, -7.40000000e+00, -7.30000000e+00,
       -7.20000000e+00, -7.10000000e+00, -7.00000000e+00, -6.90000000e+00,
       -6.80000000e+00, -6.70000000e+00, -6.60000000e+00, -6.50000000e+00,
       -6.40000000e+00, -6.30000000e+00, -6.20000000e+00, -6.10000000e+00,
       -6.00000000e+00, -5.90000000e+00, -5.80000000e+00, -5.70000000e+00,
       -5.60000000e+00, -5.50000000e+00, -5.40000000e+00, -5.30000000e+00,
       -5.20000000e+00, -5.10000000e+00, -5.00000000e+00, -4.90000000e+00,
       -4.80000000e+00, -

In [81]:
m1 = np.zeros( (6, 2) )
m1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
m2 = np.ones( (6, 10) )
m2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
m3 = np.concatenate( [m1, m2], axis=1 )
m3

array([[0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [88]:
m3.astype(np.uint8)

array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [89]:
notas = np.array( [8.2, 6.5, 9.1, 3.3] )

In [90]:
notas

array([8.2, 6.5, 9.1, 3.3])

In [92]:
np.ones_like( notas )

array([1., 1., 1., 1.])

In [115]:
np.random.seed(12)
notas = np.random.random( (4, ) )
notas = np.round(notas * 10)
notas.astype(np.uint8)

array([2, 7, 3, 5], dtype=uint8)

In [116]:
disciplinas_notas = np.random.randint(2, 11, (6, 4) )
disciplinas_notas

array([[ 2,  8,  3,  6],
       [ 7,  4,  8,  2],
       [ 7, 10,  4,  5],
       [ 6,  5,  3,  9],
       [ 2,  4,  8,  4],
       [ 2,  6,  8,  2]])

In [118]:
vet3 = np.arange(1, 100, 5)
vet3

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [124]:
vet3.reshape( (5, -1) )

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [125]:
disciplinas_notas = np.random.randint(2, 11, (6, 4) )
disciplinas_notas

array([[ 2, 10,  8,  3],
       [10,  6,  2,  6],
       [ 3,  7,  7,  5],
       [ 6,  7,  7,  2],
       [ 8,  8,  5,  4],
       [ 6,  5,  8,  9]])

In [127]:
disciplinas_notas.ravel(order='F')

array([ 2, 10,  3,  6,  8,  6, 10,  6,  7,  7,  8,  5,  8,  2,  7,  7,  5,
        8,  3,  6,  5,  2,  4,  9])

In [128]:
a = 10
b = 20
c = b
print(a) # 10
print(b) # 20
print(c) # 20

c = 5
print(a) # 10
print(b) # 20
print(c) # 5

10
20
20
10
20
5


In [129]:
a = [1, 2, 3]
b = [4, 5, 6]
c = b
print(a) # [1, 2, 3]
print(b) # [4, 5, 6]
print(c) # [4, 5, 6]

c[1] = 200
print(a) # [1, 2, 3]
print(b) # [4, 200, 6]
print(c) # [4, 200, 6]

[1, 2, 3]
[4, 5, 6]
[4, 5, 6]
[1, 2, 3]
[4, 200, 6]
[4, 200, 6]


In [142]:
vet2 = np.arange(0, 200, 5)

In [148]:
vet2

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195])

In [149]:
arr4 = vet2.reshape( (4, 10) ).view()
arr4

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195]])

In [150]:
arr4[3, 9] = 300

In [151]:
arr4

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 300]])

In [152]:
vet2

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       300])

In [161]:
caixa_ovos = np.random.randint(1, 4, (3, 4, 5))
caixa_ovos

array([[[3, 1, 1, 1, 1],
        [1, 1, 3, 3, 2],
        [1, 3, 3, 1, 1],
        [3, 1, 3, 2, 1]],

       [[3, 1, 2, 1, 2],
        [1, 1, 2, 3, 1],
        [3, 1, 1, 2, 1],
        [2, 3, 1, 3, 2]],

       [[1, 3, 3, 3, 1],
        [2, 3, 2, 3, 3],
        [1, 2, 1, 3, 3],
        [2, 2, 3, 2, 1]]])

In [162]:
caixa_ovos.T

array([[[3, 3, 1],
        [1, 1, 2],
        [1, 3, 1],
        [3, 2, 2]],

       [[1, 1, 3],
        [1, 1, 3],
        [3, 1, 2],
        [1, 3, 2]],

       [[1, 2, 3],
        [3, 2, 2],
        [3, 1, 1],
        [3, 1, 3]],

       [[1, 1, 3],
        [3, 3, 3],
        [1, 2, 3],
        [2, 3, 2]],

       [[1, 2, 1],
        [2, 1, 3],
        [1, 1, 3],
        [1, 2, 1]]])

In [164]:
caixa_ovos.transpose( (1, 2, 0) )

array([[[3, 3, 1],
        [1, 1, 3],
        [1, 2, 3],
        [1, 1, 3],
        [1, 2, 1]],

       [[1, 1, 2],
        [1, 1, 3],
        [3, 2, 2],
        [3, 3, 3],
        [2, 1, 3]],

       [[1, 3, 1],
        [3, 1, 2],
        [3, 1, 1],
        [1, 2, 3],
        [1, 1, 3]],

       [[3, 2, 2],
        [1, 3, 2],
        [3, 1, 3],
        [2, 3, 2],
        [1, 2, 1]]])

In [165]:
np.savez('caixa_ovos.npz', caixa=caixa_ovos)

In [166]:
nova_caixa_ovos = np.load('caixa_ovos.npz')['caixa']

In [167]:
nova_caixa_ovos

array([[[3, 1, 1, 1, 1],
        [1, 1, 3, 3, 2],
        [1, 3, 3, 1, 1],
        [3, 1, 3, 2, 1]],

       [[3, 1, 2, 1, 2],
        [1, 1, 2, 3, 1],
        [3, 1, 1, 2, 1],
        [2, 3, 1, 3, 2]],

       [[1, 3, 3, 3, 1],
        [2, 3, 2, 3, 3],
        [1, 2, 1, 3, 3],
        [2, 2, 3, 2, 1]]])

In [169]:
caixa_grande_ovos = nova_caixa_ovos * 2

In [170]:
caixa_grande_ovos

array([[[6, 2, 2, 2, 2],
        [2, 2, 6, 6, 4],
        [2, 6, 6, 2, 2],
        [6, 2, 6, 4, 2]],

       [[6, 2, 4, 2, 4],
        [2, 2, 4, 6, 2],
        [6, 2, 2, 4, 2],
        [4, 6, 2, 6, 4]],

       [[2, 6, 6, 6, 2],
        [4, 6, 4, 6, 6],
        [2, 4, 2, 6, 6],
        [4, 4, 6, 4, 2]]])

In [172]:
np.random.seed(100)
caixa_ovo_1 = np.random.randint(1, 4, (4, 5))
caixa_ovo_2 = np.random.randint(1, 4, (4, 5))

In [173]:
caixa_ovo_1 # 4 x 5

array([[1, 1, 1, 3, 3],
       [1, 3, 2, 3, 3],
       [3, 3, 2, 1, 1],
       [1, 1, 3, 1, 2]])

In [174]:
caixa_ovo_2  # 4 x 5

array([[2, 3, 3, 1, 1],
       [2, 2, 2, 1, 1],
       [2, 2, 2, 3, 1],
       [3, 2, 2, 3, 3]])

In [178]:
caixa_ovo_1 * caixa_ovo_2.T 

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [179]:
caixa_ovo_1 @ caixa_ovo_2.T # 4 x 5   @  5 x 4

array([[14, 12, 18, 25],
       [23, 18, 24, 31],
       [23, 18, 20, 25],
       [17, 13, 15, 20]])

In [181]:
caixa_grande = np.random.randint(1, 4, (6, 6))

In [183]:
caixa_grande

array([[2, 1, 3, 2, 3, 1],
       [2, 3, 1, 3, 1, 1],
       [3, 2, 3, 2, 1, 2],
       [3, 3, 2, 2, 1, 3],
       [1, 2, 3, 1, 2, 2],
       [1, 3, 3, 1, 3, 3]])

In [182]:
np.linalg.det(caixa_grande)

9.999999999999993

In [186]:
caixa_grande @ np.eye(6)

array([[2., 1., 3., 2., 3., 1.],
       [2., 3., 1., 3., 1., 1.],
       [3., 2., 3., 2., 1., 2.],
       [3., 3., 2., 2., 1., 3.],
       [1., 2., 3., 1., 2., 2.],
       [1., 3., 3., 1., 3., 3.]])

In [191]:
caixa_grande <= 1

array([[False,  True, False, False, False,  True],
       [False, False,  True, False,  True,  True],
       [False, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [192]:
caixa_grade_sem_ovos_peq = caixa_grande[caixa_grande > 1]
caixa_grade_sem_ovos_peq

array([2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 3,
       3, 3, 3])

In [200]:
caixa_grade_sem_ovos_peq = caixa_grade_sem_ovos_peq.reshape(5, 5)
caixa_grade_sem_ovos_peq

array([[2, 3, 2, 3, 2],
       [3, 3, 3, 2, 3],
       [2, 2, 3, 3, 2],
       [2, 3, 2, 3, 2],
       [2, 3, 3, 3, 3]])

In [208]:
np.isnan(caixa_grade_sem_ovos_peq)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [218]:
caixa_grade_sem_ovos_peq[0:5:2]

array([[2, 3, 2, 3, 2],
       [2, 2, 3, 3, 2],
       [2, 3, 3, 3, 3]])

In [220]:
caixa_grade_sem_ovos_peq.sum(axis=1)

array([12, 14, 12, 12, 14])