In [ ]:
# !pip install numpy

In [1]:
import numpy as np

In [2]:
matriz1d = np.array([1, 2, 3, 4, 5], dtype=np.float32)

In [3]:
matriz1d

array([1., 2., 3., 4., 5.], dtype=float32)

In [4]:
matriz1d.astype(np.uint8)

array([1, 2, 3, 4, 5], dtype=uint8)

In [9]:
matriz1d.ndim

1

In [10]:
matriz1d.shape

(5,)

In [11]:
matriz1d.dtype

dtype('float32')

In [12]:
uns = np.ones( (10, 20), dtype=np.float64 ) 

In [13]:
uns

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [14]:
uns.ndim

2

In [15]:
uns.shape

(10, 20)

In [18]:
v30uns = np.ones( (30, ), dtype=np.float32 )

In [20]:
v30zeros = np.zeros( (30, ), dtype=np.float32 )

In [21]:
v30uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [22]:
v30zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [24]:
impares = np.arange( 1, 101, 2 )
impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [29]:
numeros = np.arange(10, 20).astype(np.uint8)
v30zeros = np.zeros( (50, ), dtype=np.float32 )

vconc = np.concatenate( [numeros, v30zeros] )

In [30]:
vconc

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [43]:
mzeros = np.zeros( (10, 5) )
muns = np.ones( (30, 5) )

vconc = np.concatenate( [mzeros, muns], axis=0 ) 
vconc

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1.

In [45]:
vet1 = np.arange(10, 60)
vet1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [48]:
np.ones_like(vet1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [57]:
mat_aleat = np.random.randint( 5, 10, (8, 8) )
mat_aleat

array([[8, 7, 6, 9, 8, 6, 5, 9],
       [7, 6, 8, 7, 5, 9, 5, 6],
       [7, 7, 5, 8, 6, 6, 5, 6],
       [5, 9, 7, 7, 9, 8, 8, 9],
       [5, 8, 8, 6, 9, 6, 9, 9],
       [6, 7, 5, 7, 5, 6, 7, 6],
       [9, 5, 8, 8, 6, 7, 5, 5],
       [5, 7, 7, 9, 5, 5, 5, 6]])

In [52]:
mat_zeros = np.zeros_like(mat_aleat)
mat_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
mat_zeros.shape

(5, 10)

In [54]:
mat_aleat.shape

(5, 10)

In [58]:
mateye1 = np.eye(8)
mateye1

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
mat_aleat

array([[8, 7, 6, 9, 8, 6, 5, 9],
       [7, 6, 8, 7, 5, 9, 5, 6],
       [7, 7, 5, 8, 6, 6, 5, 6],
       [5, 9, 7, 7, 9, 8, 8, 9],
       [5, 8, 8, 6, 9, 6, 9, 9],
       [6, 7, 5, 7, 5, 6, 7, 6],
       [9, 5, 8, 8, 6, 7, 5, 5],
       [5, 7, 7, 9, 5, 5, 5, 6]])

In [60]:
lista1 = [10, 20, None, None, None, 40]
lista1

[10, 20, None, None, None, 40]

In [63]:
vet1 = np.array([10, 20, None, None, None, 40]).astype(np.float32)
vet1

array([10., 20., nan, nan, nan, 40.], dtype=float32)

In [66]:
matsoma = mat_aleat + mateye1
matsoma

array([[ 9.,  7.,  6.,  9.,  8.,  6.,  5.,  9.],
       [ 7.,  7.,  8.,  7.,  5.,  9.,  5.,  6.],
       [ 7.,  7.,  6.,  8.,  6.,  6.,  5.,  6.],
       [ 5.,  9.,  7.,  8.,  9.,  8.,  8.,  9.],
       [ 5.,  8.,  8.,  6., 10.,  6.,  9.,  9.],
       [ 6.,  7.,  5.,  7.,  5.,  7.,  7.,  6.],
       [ 9.,  5.,  8.,  8.,  6.,  7.,  6.,  5.],
       [ 5.,  7.,  7.,  9.,  5.,  5.,  5.,  7.]])

In [67]:
mat_subtract = mat_aleat - mateye1
mat_subtract

array([[7., 7., 6., 9., 8., 6., 5., 9.],
       [7., 5., 8., 7., 5., 9., 5., 6.],
       [7., 7., 4., 8., 6., 6., 5., 6.],
       [5., 9., 7., 6., 9., 8., 8., 9.],
       [5., 8., 8., 6., 8., 6., 9., 9.],
       [6., 7., 5., 7., 5., 5., 7., 6.],
       [9., 5., 8., 8., 6., 7., 4., 5.],
       [5., 7., 7., 9., 5., 5., 5., 5.]])

In [69]:
ex1 = np.arange(1, 11, dtype=np.uint8)
ex1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [70]:
ex2 = np.random.random( (300, 200, 3) )
ex2

array([[[0.00920367, 0.53849538, 0.8854619 ],
        [0.85892162, 0.8615275 , 0.69240192],
        [0.20046739, 0.634363  , 0.2036946 ],
        ...,
        [0.83272101, 0.61963993, 0.8697169 ],
        [0.70990538, 0.49581265, 0.57598915],
        [0.04086171, 0.70628604, 0.62481516]],

       [[0.09155535, 0.82823186, 0.48268176],
        [0.79448357, 0.35763428, 0.3592963 ],
        [0.13259454, 0.75007806, 0.66644568],
        ...,
        [0.83720884, 0.75593265, 0.08275736],
        [0.58303237, 0.27205545, 0.93640469],
        [0.11427073, 0.0274459 , 0.59247952]],

       [[0.13114383, 0.63655144, 0.53757027],
        [0.65316537, 0.91898185, 0.86512919],
        [0.66655771, 0.4598873 , 0.22542531],
        ...,
        [0.03144034, 0.64055513, 0.54191205],
        [0.42011162, 0.33895822, 0.18176284],
        [0.09902405, 0.24595164, 0.22035266]],

       ...,

       [[0.27491991, 0.8096606 , 0.05466869],
        [0.73794678, 0.84300501, 0.2221841 ],
        [0.74122753, 0

In [71]:
notas = np.random.randint(1, 11, (20, 3), dtype=np.uint8)
notas

array([[ 1,  7,  7],
       [ 2,  7,  2],
       [ 1,  2,  2],
       [ 1,  4,  7],
       [ 6, 10,  7],
       [ 4,  2,  4],
       [10,  4,  1],
       [ 8,  5,  2],
       [ 3, 10,  4],
       [ 5,  5,  6],
       [ 6,  5,  7],
       [ 5,  9,  1],
       [10,  1,  3],
       [ 5,  7,  7],
       [ 2,  8, 10],
       [ 1,  7,  7],
       [ 9,  2,  6],
       [ 4,  1,  1],
       [ 5,  8,  9],
       [ 8,  7,  8]], dtype=uint8)

In [73]:
notas.ndim

2

In [75]:
vet2 = np.random.randint(1, 100, (300,))
vet2

array([92, 22, 55, 53, 94,  6, 28, 39, 62, 18, 59, 95, 37, 24, 78, 35, 37,
       11, 23, 67, 75, 43, 62, 81, 34, 50, 60, 46, 11, 11, 67, 85, 38, 18,
       94, 94, 93, 29, 68, 11, 52,  9, 55,  1, 96, 45, 98, 79, 90, 64, 95,
       82, 88, 81, 40, 44, 61,  9, 43, 51, 29, 15, 74, 18, 17, 53, 52, 36,
       90, 24, 58, 68, 58, 31, 74, 44, 52, 30, 28, 25, 66, 11, 31, 81, 40,
       27, 58, 98, 78, 36, 80, 68, 37, 95, 33, 14, 69,  9, 99, 58, 75, 92,
       46, 81, 64, 60, 79, 80, 23, 99, 37, 48, 52, 46, 33, 68, 89, 70, 97,
       88, 18, 61, 57, 28, 16, 81, 76, 25, 64, 67, 20,  9, 83,  2, 83, 57,
       33, 96, 35, 59, 45, 64, 18, 28, 21, 34, 43, 94, 56, 31, 30, 18,  6,
       90, 92, 40, 77, 85,  5, 99, 15, 72,  5, 69, 76, 65, 43, 52, 86, 86,
       83,  2, 66, 85, 46,  5, 97, 27, 70, 85, 73, 42, 44, 96, 13, 59, 39,
       16,  7, 75, 96, 87, 67, 60, 50, 87, 17, 43,  1, 43, 57, 22,  4, 65,
       93,  2, 56, 30, 84, 72, 31, 91, 69, 21, 97, 14, 37,  8, 15, 50, 32,
       20, 72,  5, 15, 44

In [77]:
mat6x50 = vet2.reshape( (6, 50) )
mat6x50

array([[92, 22, 55, 53, 94,  6, 28, 39, 62, 18, 59, 95, 37, 24, 78, 35,
        37, 11, 23, 67, 75, 43, 62, 81, 34, 50, 60, 46, 11, 11, 67, 85,
        38, 18, 94, 94, 93, 29, 68, 11, 52,  9, 55,  1, 96, 45, 98, 79,
        90, 64],
       [95, 82, 88, 81, 40, 44, 61,  9, 43, 51, 29, 15, 74, 18, 17, 53,
        52, 36, 90, 24, 58, 68, 58, 31, 74, 44, 52, 30, 28, 25, 66, 11,
        31, 81, 40, 27, 58, 98, 78, 36, 80, 68, 37, 95, 33, 14, 69,  9,
        99, 58],
       [75, 92, 46, 81, 64, 60, 79, 80, 23, 99, 37, 48, 52, 46, 33, 68,
        89, 70, 97, 88, 18, 61, 57, 28, 16, 81, 76, 25, 64, 67, 20,  9,
        83,  2, 83, 57, 33, 96, 35, 59, 45, 64, 18, 28, 21, 34, 43, 94,
        56, 31],
       [30, 18,  6, 90, 92, 40, 77, 85,  5, 99, 15, 72,  5, 69, 76, 65,
        43, 52, 86, 86, 83,  2, 66, 85, 46,  5, 97, 27, 70, 85, 73, 42,
        44, 96, 13, 59, 39, 16,  7, 75, 96, 87, 67, 60, 50, 87, 17, 43,
         1, 43],
       [57, 22,  4, 65, 93,  2, 56, 30, 84, 72, 31, 91, 69, 21, 97, 

In [78]:
print("Vet2 Shape: ", vet2.shape)
print("mat6x50 Shape: ", mat6x50.shape)

Vet2 Shape:  (300,)
mat6x50 Shape:  (6, 50)


In [81]:
mat30 = vet2.reshape( (30, 5, -1) )
mat30

array([[[92, 22],
        [55, 53],
        [94,  6],
        [28, 39],
        [62, 18]],

       [[59, 95],
        [37, 24],
        [78, 35],
        [37, 11],
        [23, 67]],

       [[75, 43],
        [62, 81],
        [34, 50],
        [60, 46],
        [11, 11]],

       [[67, 85],
        [38, 18],
        [94, 94],
        [93, 29],
        [68, 11]],

       [[52,  9],
        [55,  1],
        [96, 45],
        [98, 79],
        [90, 64]],

       [[95, 82],
        [88, 81],
        [40, 44],
        [61,  9],
        [43, 51]],

       [[29, 15],
        [74, 18],
        [17, 53],
        [52, 36],
        [90, 24]],

       [[58, 68],
        [58, 31],
        [74, 44],
        [52, 30],
        [28, 25]],

       [[66, 11],
        [31, 81],
        [40, 27],
        [58, 98],
        [78, 36]],

       [[80, 68],
        [37, 95],
        [33, 14],
        [69,  9],
        [99, 58]],

       [[75, 92],
        [46, 81],
        [64, 60],
        [79, 80],
        

In [91]:
notas = np.random.randint(1, 11, (10, 3), dtype=np.uint8)
notas

array([[ 5,  3,  2],
       [ 4,  2,  8],
       [ 8,  5, 10],
       [ 1,  5,  5],
       [10,  9,  4],
       [ 2,  8,  2],
       [ 8,  8,  1],
       [ 7,  2,  9],
       [ 4,  8,  1],
       [ 9,  9,  1]], dtype=uint8)

In [92]:
todas_notas = notas.reshape( (-1,) )
todas_notas

array([ 5,  3,  2,  4,  2,  8,  8,  5, 10,  1,  5,  5, 10,  9,  4,  2,  8,
        2,  8,  8,  1,  7,  2,  9,  4,  8,  1,  9,  9,  1], dtype=uint8)

In [90]:
notas.ravel(order='F')

array([ 9,  8,  8,  3,  8,  6,  4,  3, 10,  5,  1,  9,  9,  8,  6,  9,  9,
        9,  7,  1,  7,  9,  2,  7,  4,  9,  7, 10,  4,  8], dtype=uint8)

In [110]:
np.random.seed(50)
notas = np.random.randint(1, 11, (10, 3), dtype=np.uint8)

In [111]:
notas

array([[1, 7, 1],
       [6, 2, 2],
       [8, 4, 9],
       [4, 2, 7],
       [2, 8, 5],
       [5, 1, 6],
       [6, 7, 9],
       [6, 6, 9],
       [8, 1, 7],
       [1, 7, 7]], dtype=uint8)

In [121]:
novo_formato_notas_view = notas.reshape((6, -1))

In [123]:
novo_formato_notas_view

array([[1, 7, 1, 6, 2],
       [2, 8, 4, 9, 4],
       [2, 7, 2, 8, 5],
       [5, 1, 6, 6, 7],
       [9, 6, 6, 9, 8],
       [1, 7, 1, 7, 7]], dtype=uint8)

In [122]:
novo_formato_notas_copia = notas.reshape((6, -1)).copy()

In [124]:
novo_formato_notas_copia

array([[1, 7, 1, 6, 2],
       [2, 8, 4, 9, 4],
       [2, 7, 2, 8, 5],
       [5, 1, 6, 6, 7],
       [9, 6, 6, 9, 8],
       [1, 7, 1, 7, 7]], dtype=uint8)

In [127]:
novo_formato_notas_view[1, 4] = 200

In [128]:
novo_formato_notas_view

array([[  1,   7,   1,   6,   2],
       [  2,   8,   4, 200, 200],
       [  2,   7,   2,   8,   5],
       [  5,   1,   6,   6,   7],
       [  9,   6,   6,   9,   8],
       [  1,   7,   1,   7,   7]], dtype=uint8)

In [129]:
notas

array([[  1,   7,   1],
       [  6,   2,   2],
       [  8,   4, 200],
       [200,   2,   7],
       [  2,   8,   5],
       [  5,   1,   6],
       [  6,   7,   9],
       [  6,   6,   9],
       [  8,   1,   7],
       [  1,   7,   7]], dtype=uint8)

In [132]:
a = 10    # 10
b = 20    # 20
c = a     # 10
c = 5     # 5
print(a)  # 10
print(c)  # 5

10
5


In [133]:
lista = [1, 4, 6]

outra_lista = lista
#           lista   ----------->     [1, 4, 6]
#         outra_lista -----------------^

print(lista)        # [1, 4, 6]
print(outra_lista)  # [1, 4, 6]

outra_lista[0] = 12

print(lista)        # [12, 4, 6]
print(outra_lista)  # [12, 4, 6]

[1, 4, 6]
[1, 4, 6]
[12, 4, 6]
[12, 4, 6]


In [164]:
arr1 = np.arange(36).reshape(4, 3, 3)

In [165]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [170]:
arr1.transpose( (2, 1, 0) )

array([[[ 0,  9, 18, 27],
        [ 3, 12, 21, 30],
        [ 6, 15, 24, 33]],

       [[ 1, 10, 19, 28],
        [ 4, 13, 22, 31],
        [ 7, 16, 25, 34]],

       [[ 2, 11, 20, 29],
        [ 5, 14, 23, 32],
        [ 8, 17, 26, 35]]])

In [169]:
arr1.T

array([[[ 0,  9, 18, 27],
        [ 3, 12, 21, 30],
        [ 6, 15, 24, 33]],

       [[ 1, 10, 19, 28],
        [ 4, 13, 22, 31],
        [ 7, 16, 25, 34]],

       [[ 2, 11, 20, 29],
        [ 5, 14, 23, 32],
        [ 8, 17, 26, 35]]])

In [178]:
np.savez('notas.npz', matriz=arr1)

In [179]:
arr2 = np.load('notas.npz')['matriz']

In [180]:
arr2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [181]:
arr2 * 2

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]],

       [[36, 38, 40],
        [42, 44, 46],
        [48, 50, 52]],

       [[54, 56, 58],
        [60, 62, 64],
        [66, 68, 70]]])

In [182]:
ar1 = np.arange(30)
ar2 = np.random.randint(1, 60, (30,))
print(ar1)
print(ar2)
print(ar1 * ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[23 46  6  3 32 59  8 48  5 15 36 29 28 27 27  7 21 44 32 50 22 43 42  1
  7 20  3 16 31 42]
[   0   46   12    9  128  295   48  336   40  135  360  319  336  351
  378  105  336  748  576  950  440  903  924   23  168  500   78  432
  868 1218]


In [183]:
ar2 > 50

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [184]:
ar1 *= 2

In [185]:
ar1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [186]:
ar3 = ar1 ** (1/2)

In [187]:
ar3

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ,
       6.32455532, 6.4807407 , 6.63324958, 6.78232998, 6.92820323,
       7.07106781, 7.21110255, 7.34846923, 7.48331477, 7.61577311])

In [195]:
ar3[0] = np.nan

In [196]:
ar3

array([       nan, 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ,
       6.32455532, 6.4807407 , 6.63324958, 6.78232998, 6.92820323,
       7.07106781, 7.21110255, 7.34846923, 7.48331477, 7.61577311])

In [197]:
np.isnan(ar3)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [202]:
ar5 = ar3.reshape((5, -1))

In [203]:
ar5

array([[       nan, 1.41421356, 2.        , 2.44948974, 2.82842712,
        3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
        4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558, 5.65685425,
        5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 , 6.63324958,
        6.78232998],
       [6.92820323, 7.07106781, 7.21110255, 7.34846923, 7.48331477,
        7.61577311]])

In [210]:
ar5[:, 2:3]

array([[2.        ],
       [4.        ],
       [5.29150262],
       [6.32455532],
       [7.21110255]])

In [212]:
ar5[:, 2:3].ravel()

array([2.        , 4.        , 5.29150262, 6.32455532, 7.21110255])

In [213]:
ar5

array([[       nan, 1.41421356, 2.        , 2.44948974, 2.82842712,
        3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
        4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558, 5.65685425,
        5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 , 6.63324958,
        6.78232998],
       [6.92820323, 7.07106781, 7.21110255, 7.34846923, 7.48331477,
        7.61577311]])

In [215]:
ar5[ar5<3] = 0

In [216]:
ar5

array([[       nan, 0.        , 0.        , 0.        , 0.        ,
        3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
        4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558, 5.65685425,
        5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 , 6.63324958,
        6.78232998],
       [6.92820323, 7.07106781, 7.21110255, 7.34846923, 7.48331477,
        7.61577311]])

In [218]:
ar5[np.isnan(ar5)] = 0

In [219]:
ar5

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
        4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558, 5.65685425,
        5.83095189],
       [6.        , 6.164414  , 6.32455532, 6.4807407 , 6.63324958,
        6.78232998],
       [6.92820323, 7.07106781, 7.21110255, 7.34846923, 7.48331477,
        7.61577311]])

In [228]:
np.median(ar5, axis=1)

array([0.        , 4.12132034, 5.3843641 , 6.40264801, 7.27978589])

In [229]:
mat1 = np.random.randint(1, 10, (2, 3))

In [230]:
mat2 = np.random.randint(1, 10, (2, 3))

In [238]:
mat1

array([[4, 4, 4],
       [3, 1, 4]])

In [237]:
mat2

array([[3, 1, 4],
       [1, 1, 8]])

In [239]:
np.matmul(mat1.T, mat2)

array([[15,  7, 40],
       [13,  5, 24],
       [16,  8, 48]])

In [243]:
mat1.T @ mat2

array([[15,  7, 40],
       [13,  5, 24],
       [16,  8, 48]])

In [245]:
v1 = mat1.ravel()
v1

array([4, 4, 4, 3, 1, 4])

In [246]:
v2 = mat2.ravel()
v2

array([3, 1, 4, 1, 1, 8])

In [247]:
np.dot(v1, v2)

68